/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Uploads
         * @description Recent uploads, newest first, each with how its citations came out.
         */
        get: operations["list_uploads_uploads_get"];
        put?: never;
        /**
         * Create Upload
         * @description Upload a PDF/DOCX. Known citations are checked now; the rest finish in the
         *     background (poll GET /uploads/{id}). 202 means "still processing".
         */
        post: operations["create_upload_uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/{upload_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Upload */
        get: operations["get_upload_uploads__upload_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/{upload_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry Upload
         * @description Check again the citations that could not be checked (source down, page unreadable).
         */
        post: operations["retry_upload_uploads__upload_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/{upload_id}/citations/{citation_id}/attach": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Attach Case
         * @description The student pastes the Lawphil link for a citation that could not be found.
         */
        post: operations["attach_case_uploads__upload_id__citations__citation_id__attach_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Cases
         * @description Search by G.R. number. A case we do not have yet is fetched in the background:
         *     202 + status "pending" means ask again shortly.
         */
        get: operations["search_cases_cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/fetch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fetch Case By Url
         * @description Manual fallback: fetch and store one official Lawphil page by its URL.
         */
        post: operations["fetch_case_by_url_cases_fetch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Case */
        get: operations["get_case_cases__case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Library Cases
         * @description Every stored case, newest decision first. Lighter than GET /cases/{id}: no full text.
         */
        get: operations["library_cases_library_cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Catalog
         * @description Search every decision on Lawphil's lists, 1987 to now, by case name or G.R. number.
         *
         *     Answers from our own copy of the lists, so it is instant. Using it also keeps that copy
         *     fresh: the first search starts the one-time build; later searches ask for a refresh of
         *     the newest months at most once a day.
         */
        get: operations["search_catalog_catalog_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalog Status */
        get: operations["catalog_status_catalog_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/build": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Build Catalog
         * @description Start (or resume) reading Lawphil's monthly lists. Takes about 9 minutes the first time;
         *     a second request while one runs does nothing.
         */
        post: operations["build_catalog_catalog_build_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Case Insights
         * @description Key findings for one stored case, parsed from its official text.
         */
        get: operations["case_insights_cases__case_id__insights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/insights/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Trends
         * @description Patterns across every stored decision. `enough_data` is false until there are
         *     enough cases for the counts to mean anything.
         */
        get: operations["trends_insights_trends_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}/digest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Case Digest */
        get: operations["get_case_digest_cases__case_id__digest_get"];
        put?: never;
        /**
         * Request Digest
         * @description Start (or return) this case's digest. The Court's own text is in the response at once; the written
         *     explanations arrive in the background (status `pending`, each answer field `pending` until ready): poll
         *     `GET /digests/{id}`.
         */
        post: operations["request_digest_cases__case_id__digest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/{upload_id}/digests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Upload Digests */
        get: operations["list_upload_digests_uploads__upload_id__digests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/digests/{digest_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Digest */
        get: operations["get_digest_digests__digest_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/digests/{digest_id}/fields/{key}/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Write Field
         * @description The student types over a field. It is marked as theirs; `reset` puts the system's version back.
         */
        put: operations["write_field_digests__digest_id__fields__key__text_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/digests/{digest_id}/fields/{key}/paste": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Paste Field
         * @description The student pastes text into a Court-text field (Facts, Issue, Ruling, Doctrine). Marked as pasted.
         */
        post: operations["paste_field_digests__digest_id__fields__key__paste_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/digests/{digest_id}/fields/{key}/passage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Pick Passage
         * @description The student picks paragraphs of the decision. The text is read from the stored decision, never from the request.
         */
        put: operations["pick_passage_digests__digest_id__fields__key__passage_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/digests/{digest_id}/fields/{key}/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Field */
        post: operations["reset_field_digests__digest_id__fields__key__reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/digests/{digest_id}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask Question
         * @description Add a question of the student's own (any question in their reviewer). It is answered in the background.
         */
        post: operations["ask_question_digests__digest_id__questions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/digests/{digest_id}/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Regenerate */
        post: operations["regenerate_digests__digest_id__regenerate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/{upload_id}/document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Finished Reviewer
         * @description The reviewer's paragraphs with the digest boxes placed after the paragraph that cites each case.
         *     Fetch each box's content with `GET /digests/{id}`.
         */
        get: operations["finished_reviewer_uploads__upload_id__document_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/{upload_id}/document.docx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Finished Reviewer
         * @description The finished reviewer as a Word file. Anything still being written is marked, so download again a moment later.
         */
        get: operations["download_finished_reviewer_uploads__upload_id__document_docx_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Attribution
         * @description Shown with every response that presents official text. Wording follows Lawphil's own
         *     Acceptable Use Policy and Disclaimer (read 2026-10-03): informational only, no warranty
         *     of accuracy or completeness, confirm with the originating body.
         */
        Attribution: {
            /**
             * Source
             * @default Lawphil (Arellano Law Foundation), https://lawphil.net
             */
            source: string;
            /**
             * Notice
             * @default Informational only, not legal advice. Lawphil gives no warranty of accuracy or completeness: confirm with the originating body (the Supreme Court).
             */
            notice: string;
        };
        /** BlockOut */
        BlockOut: {
            /** Index */
            index: number;
            /** Text */
            text: string;
            /** Heading Level */
            heading_level: number | null;
            /** Boxes */
            boxes: components["schemas"]["BoxRefOut"][];
        };
        /** Body_create_upload_uploads_post */
        Body_create_upload_uploads_post: {
            /** File */
            file: string;
        };
        /** BoxRefOut */
        BoxRefOut: {
            /** Digest Id */
            digest_id: number;
            /** Case Id */
            case_id: number;
            /** Citation Id */
            citation_id: number;
            /** Title */
            title: string;
            /** Heading */
            heading: string;
            /** Ready */
            ready: boolean;
        };
        /** CaseDetailOut */
        CaseDetailOut: {
            /** Id */
            id: number;
            /** Gr No */
            gr_no: string;
            /** Title */
            title: string | null;
            /** Decision Date */
            decision_date: string | null;
            /**
             * Doc Type
             * @enum {string}
             */
            doc_type: "decision" | "resolution" | "separate_opinion" | "unknown";
            /** Ponente */
            ponente: string | null;
            /** Division */
            division: string | null;
            /**
             * Disposition
             * @enum {string}
             */
            disposition: "GRANTED" | "DENIED" | "PARTIALLY_GRANTED" | "DISMISSED" | "AFFIRMED" | "REVERSED" | "UNKNOWN";
            /** Source Url */
            source_url: string;
            /** Full Text */
            full_text: string;
            /** Fetched At */
            fetched_at: string | null;
            /**
             * @default {
             *       "source": "Lawphil (Arellano Law Foundation), https://lawphil.net",
             *       "notice": "Informational only, not legal advice. Lawphil gives no warranty of accuracy or completeness: confirm with the originating body (the Supreme Court)."
             *     }
             */
            attribution: components["schemas"]["Attribution"];
            /** Footnotes */
            footnotes: components["schemas"]["FootnoteOut"][];
            /** Opinions */
            opinions: components["schemas"]["OpinionOut"][];
            /** Statutes */
            statutes: components["schemas"]["StatuteOut"][];
            /** Cited Cases */
            cited_cases: components["schemas"]["CitedCaseOut"][];
        };
        /** CasePageOut */
        CasePageOut: {
            /** Items */
            items: components["schemas"]["CaseSummaryOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** CaseSummaryOut */
        CaseSummaryOut: {
            /** Id */
            id: number;
            /** Gr No */
            gr_no: string;
            /** Title */
            title: string | null;
            /** Decision Date */
            decision_date: string | null;
            /**
             * Doc Type
             * @enum {string}
             */
            doc_type: "decision" | "resolution" | "separate_opinion" | "unknown";
            /** Ponente */
            ponente: string | null;
            /** Division */
            division: string | null;
            /**
             * Disposition
             * @enum {string}
             */
            disposition: "GRANTED" | "DENIED" | "PARTIALLY_GRANTED" | "DISMISSED" | "AFFIRMED" | "REVERSED" | "UNKNOWN";
            /** Source Url */
            source_url: string;
        };
        /** CatalogBuildOut */
        CatalogBuildOut: {
            /** Started */
            started: boolean;
            catalog: components["schemas"]["CatalogStatusOut"];
        };
        /**
         * CatalogItemOut
         * @description One decision on Lawphil's lists. Opening it saves the full case into the library.
         */
        CatalogItemOut: {
            /** Title */
            title: string;
            /** Gr No */
            gr_no: string;
            /** Numbers */
            numbers: string[];
            /** Also Decided With */
            also_decided_with: string[];
            /** Decision Date */
            decision_date: string | null;
            /** Source Url */
            source_url: string;
            /** Case Id */
            case_id: number | null;
            /** In Library */
            in_library: boolean;
        };
        /** CatalogSearchOut */
        CatalogSearchOut: {
            /**
             * Understood As
             * @enum {string}
             */
            understood_as: "number" | "name" | "nothing";
            /** Items */
            items: components["schemas"]["CatalogItemOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            catalog: components["schemas"]["CatalogStatusOut"];
            /**
             * @default {
             *       "source": "Lawphil (Arellano Law Foundation), https://lawphil.net",
             *       "notice": "Informational only, not legal advice. Lawphil gives no warranty of accuracy or completeness: confirm with the originating body (the Supreme Court)."
             *     }
             */
            attribution: components["schemas"]["Attribution"];
        };
        /**
         * CatalogStatusOut
         * @description How far the searchable copy of Lawphil's lists has got.
         */
        CatalogStatusOut: {
            /**
             * State
             * @enum {string}
             */
            state: "empty" | "building" | "partial" | "ready";
            /** Entries */
            entries: number;
            /** Months Read */
            months_read: number;
            /** Months Known */
            months_known: number;
            /** Percent */
            percent: number;
        };
        /** CitationOut */
        CitationOut: {
            /** Id */
            id: number;
            /** Gr No */
            gr_no: string;
            /** Raw Citation */
            raw_citation: string;
            claimed: components["schemas"]["ClaimedOut"];
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "match" | "mismatch" | "not_found" | "error";
            /** Mismatches */
            mismatches: {
                [key: string]: components["schemas"]["MismatchOut"];
            };
            /** Unverified */
            unverified: string[];
            /** Message */
            message: string | null;
            /** Case Id */
            case_id: number | null;
            /** Source Url */
            source_url: string | null;
            case: components["schemas"]["CaseSummaryOut"] | null;
        };
        /** CitedCaseCountOut */
        CitedCaseCountOut: {
            /** Title */
            title: string;
            /** Gr No */
            gr_no: string | null;
            /** Cases */
            cases: number;
        };
        /** CitedCaseOut */
        CitedCaseOut: {
            /** Title */
            title: string;
            /** Gr No */
            gr_no: string | null;
            /** Source */
            source: string;
            /** Footnote Number */
            footnote_number?: number | null;
            /** Source Url */
            source_url?: string | null;
        };
        /** ClaimedOut */
        ClaimedOut: {
            /** Title */
            title: string | null;
            /** Year */
            year: number | null;
            /** Date */
            date: string | null;
            /** Reporter */
            reporter: string | null;
        };
        /** DigestFieldOut */
        DigestFieldOut: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "verbatim" | "answer" | "note";
            /** Text */
            text: string;
            /**
             * Origin
             * @enum {string}
             */
            origin: "court_heading" | "court_ruling" | "student_picked" | "student_pasted" | "ai_drafted" | "student_written" | "empty";
            /**
             * State
             * @enum {string}
             */
            state: "ready" | "pending" | "unavailable";
            /** Cites */
            cites: string[];
            passage: components["schemas"]["PassageOut"] | null;
            /** Question */
            question: string | null;
            /** Note */
            note: string | null;
            /** Edited */
            edited: boolean;
            /** Can Reset */
            can_reset: boolean;
        };
        /** DigestOut */
        DigestOut: {
            /** Id */
            id: number;
            /** Case Id */
            case_id: number;
            /** Upload Id */
            upload_id: number | null;
            /**
             * Template
             * @enum {string}
             */
            template: "facts_and_doctrine" | "full";
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "ready" | "failed";
            /** Error */
            error: string | null;
            /** Case Title */
            case_title: string | null;
            /** Gr No */
            gr_no: string;
            /** Decision Date */
            decision_date: string | null;
            /** Source Url */
            source_url: string;
            /** Fields */
            fields: components["schemas"]["DigestFieldOut"][];
            /** Pickable First */
            pickable_first: number | null;
            /** Pickable Last */
            pickable_last: number | null;
            /**
             * @default {
             *       "source": "Lawphil (Arellano Law Foundation), https://lawphil.net",
             *       "notice": "Informational only, not legal advice. Lawphil gives no warranty of accuracy or completeness: confirm with the originating body (the Supreme Court)."
             *     }
             */
            attribution: components["schemas"]["Attribution"];
        };
        /** DigestRequestIn */
        DigestRequestIn: {
            /** Upload Id */
            upload_id?: number | null;
            /**
             * Template
             * @default full
             * @enum {string}
             */
            template: "facts_and_doctrine" | "full";
            /** Questions */
            questions?: string[];
        };
        /** DispositionCountOut */
        DispositionCountOut: {
            /** Year */
            year: number;
            /**
             * Disposition
             * @enum {string}
             */
            disposition: "GRANTED" | "DENIED" | "PARTIALLY_GRANTED" | "DISMISSED" | "AFFIRMED" | "REVERSED" | "UNKNOWN";
            /** Cases */
            cases: number;
        };
        /** FetchByUrlIn */
        FetchByUrlIn: {
            /** Url */
            url: string;
        };
        /** FinishedReviewerOut */
        FinishedReviewerOut: {
            /** Upload Id */
            upload_id: number;
            /** Filename */
            filename: string;
            /** Source */
            source: string;
            /** Blocks */
            blocks: components["schemas"]["BlockOut"][];
            /** Unplaced */
            unplaced: components["schemas"]["BoxRefOut"][];
            /** All Ready */
            all_ready: boolean;
            /** Own Digests */
            own_digests: number;
        };
        /** FootnoteOut */
        FootnoteOut: {
            /** Number */
            number: number;
            /** Anchor */
            anchor: string;
            /** Text */
            text: string;
            /** Source Url */
            source_url?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InsightsOut
         * @description Findings parsed from the stored official text. Nothing here is generated.
         */
        InsightsOut: {
            /** Case Id */
            case_id: number;
            /** Gr No */
            gr_no: string;
            /** Title */
            title: string | null;
            /** Source Url */
            source_url: string;
            /** Decision Date */
            decision_date: string | null;
            /**
             * Doc Type
             * @enum {string}
             */
            doc_type: "decision" | "resolution" | "separate_opinion" | "unknown";
            /** Division */
            division: string | null;
            /** Ponente */
            ponente: string | null;
            /**
             * Disposition
             * @enum {string}
             */
            disposition: "GRANTED" | "DENIED" | "PARTIALLY_GRANTED" | "DISMISSED" | "AFFIRMED" | "REVERSED" | "UNKNOWN";
            /** Ruling */
            ruling: string | null;
            /** Concurring Justices */
            concurring_justices: string[];
            /** Opinions */
            opinions: components["schemas"]["OpinionRefOut"][];
            /** Statutes */
            statutes: components["schemas"]["StatuteOut"][];
            /** Cited Cases */
            cited_cases: components["schemas"]["CitedCaseOut"][];
            /** Footnote Count */
            footnote_count: number;
            /** Word Count */
            word_count: number;
            /**
             * @default {
             *       "source": "Lawphil (Arellano Law Foundation), https://lawphil.net",
             *       "notice": "Informational only, not legal advice. Lawphil gives no warranty of accuracy or completeness: confirm with the originating body (the Supreme Court)."
             *     }
             */
            attribution: components["schemas"]["Attribution"];
        };
        /**
         * MismatchOut
         * @description One field where the student's citation differs from the official record.
         */
        MismatchOut: {
            /** Claimed */
            claimed: string | number | null;
            /** Official */
            official: string | number | null;
        };
        /** OpinionOut */
        OpinionOut: {
            /** Kind */
            kind: string;
            /** Author */
            author: string | null;
            /** Text */
            text: string;
            /** Footnotes */
            footnotes: components["schemas"]["FootnoteOut"][];
        };
        /** OpinionRefOut */
        OpinionRefOut: {
            /** Kind */
            kind: string;
            /** Author */
            author: string | null;
        };
        /** PassageIn */
        PassageIn: {
            /** First */
            first: number;
            /** Last */
            last: number;
        };
        /** PassageOut */
        PassageOut: {
            /** First */
            first: number;
            /** Last */
            last: number;
        };
        /** PonenteCountOut */
        PonenteCountOut: {
            /** Ponente */
            ponente: string;
            /** Cases */
            cases: number;
        };
        /** QuestionIn */
        QuestionIn: {
            /** Question */
            question: string;
        };
        /** RegenerateIn */
        RegenerateIn: {
            /** Keys */
            keys: string[];
        };
        /** SearchOut */
        SearchOut: {
            /**
             * Status
             * @enum {string}
             */
            status: "found" | "pending" | "needs_year";
            /** Cases */
            cases: components["schemas"]["CaseSummaryOut"][];
        };
        /** StatuteCountOut */
        StatuteCountOut: {
            /** Statute Type */
            statute_type: string;
            /** Number */
            number: string;
            /** Cases */
            cases: number;
        };
        /** StatuteOut */
        StatuteOut: {
            /** Type */
            type: string;
            /** Number */
            number: string;
            /** Raw */
            raw: string;
        };
        /** TextIn */
        TextIn: {
            /** Text */
            text: string;
        };
        /** TrendsOut */
        TrendsOut: {
            /** Total Cases */
            total_cases: number;
            /** Minimum Cases */
            minimum_cases: number;
            /** Enough Data */
            enough_data: boolean;
            /** Message */
            message: string;
            /** Top Statutes */
            top_statutes: components["schemas"]["StatuteCountOut"][];
            /** Dispositions By Year */
            dispositions_by_year: components["schemas"]["DispositionCountOut"][];
            /** Most Cited Cases */
            most_cited_cases: components["schemas"]["CitedCaseCountOut"][];
            /** Cases Per Ponente */
            cases_per_ponente: components["schemas"]["PonenteCountOut"][];
        };
        /** UploadOut */
        UploadOut: {
            /** Id */
            id: number;
            /** Filename */
            filename: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "processing" | "done";
            /** Created At */
            created_at: string | null;
            /** Citations */
            citations: components["schemas"]["CitationOut"][];
            /**
             * @default {
             *       "source": "Lawphil (Arellano Law Foundation), https://lawphil.net",
             *       "notice": "Informational only, not legal advice. Lawphil gives no warranty of accuracy or completeness: confirm with the originating body (the Supreme Court)."
             *     }
             */
            attribution: components["schemas"]["Attribution"];
        };
        /** UploadSummaryOut */
        UploadSummaryOut: {
            /** Id */
            id: number;
            /** Filename */
            filename: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "processing" | "done";
            /** Created At */
            created_at: string | null;
            /** Total */
            total: number;
            /** Matched */
            matched: number;
            /** Needs Look */
            needs_look: number;
            /** Not Found */
            not_found: number;
            /** Errors */
            errors: number;
            /** Pending */
            pending: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_uploads_uploads_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSummaryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_upload_uploads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_upload_uploads_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_upload_uploads__upload_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_upload_uploads__upload_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    attach_case_uploads__upload_id__citations__citation_id__attach_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: number;
                citation_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FetchByUrlIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_cases_cases_get: {
        parameters: {
            query: {
                gr_no: string;
                year?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fetch_case_by_url_cases_fetch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FetchByUrlIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_case_cases__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    library_cases_library_cases_get: {
        parameters: {
            query?: {
                /** @description Part of the case name, or the start of a G.R. number */
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CasePageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_catalog_catalog_search_get: {
        parameters: {
            query: {
                /** @description Words from a case name, or a G.R. number */
                q: string;
                year?: number | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogSearchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    catalog_status_catalog_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogStatusOut"];
                };
            };
        };
    };
    build_catalog_catalog_build_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogBuildOut"];
                };
            };
        };
    };
    case_insights_cases__case_id__insights_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trends_insights_trends_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_case_digest_cases__case_id__digest_get: {
        parameters: {
            query?: {
                upload_id?: number | null;
            };
            header?: never;
            path: {
                case_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DigestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_digest_cases__case_id__digest_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DigestRequestIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DigestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_upload_digests_uploads__upload_id__digests_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DigestOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_digest_digests__digest_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                digest_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DigestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    write_field_digests__digest_id__fields__key__text_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                digest_id: number;
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TextIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DigestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    paste_field_digests__digest_id__fields__key__paste_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                digest_id: number;
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TextIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DigestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pick_passage_digests__digest_id__fields__key__passage_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                digest_id: number;
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PassageIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DigestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_field_digests__digest_id__fields__key__reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                digest_id: number;
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DigestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_question_digests__digest_id__questions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                digest_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DigestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regenerate_digests__digest_id__regenerate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                digest_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegenerateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DigestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finished_reviewer_uploads__upload_id__document_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinishedReviewerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_finished_reviewer_uploads__upload_id__document_docx_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
