"""desktop baseline: every table of the desktop app's SQLite database, made from the models (the web version's PostgreSQL
schema has its own history in backend/alembic). The trigram, full-text and array indexes are PostgreSQL-only and left out.

Revision ID: s0001
Revises: 
"""
from alembic import op
import sqlalchemy as sa

from caselens.domain.subjects import DEFAULT_SUBJECTS

revision = 's0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulk_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_ids', sa.JSON(), nullable=False),
    sa.Column('topic_scope', sa.String(length=300), server_default='', nullable=False),
    sa.Column('kind', sa.String(length=16), server_default='bulk', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gr_no', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('decision_date', sa.Date(), nullable=True),
    sa.Column('doc_type', sa.String(length=32), server_default='decision', nullable=False),
    sa.Column('ponente', sa.String(length=128), nullable=True),
    sa.Column('division', sa.String(length=64), nullable=True),
    sa.Column('disposition', sa.String(length=32), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('raw_html', sa.Text(), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('parser_version', sa.Integer(), nullable=False),
    sa.Column('numbers', sa.JSON(), nullable=False),
    sa.Column('main_case_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['main_case_id'], ['cases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url')
    )
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cases_gr_no'), ['gr_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_main_case_id'), ['main_case_id'], unique=False)
        batch_op.create_index('ix_cases_title_trgm', ['title'], unique=False)

    op.create_table('catalog_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('link_number', sa.String(length=32), nullable=False),
    sa.Column('label_key', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('decision_date', sa.Date(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('index_url', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url', 'label_key', name='uq_catalog_entries_row')
    )
    with op.batch_alter_table('catalog_entries', schema=None) as batch_op:
        batch_op.create_index('ix_catalog_entries_title_trgm', ['title'], unique=False)
        batch_op.create_index('ix_catalog_entries_year_month', ['year', 'month'], unique=False)

    op.create_table('catalog_months',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('entries', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('year', 'month')
    )
    op.create_table('job_locks',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('month_indexes',
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('links', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('url')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('file_data', sa.LargeBinary(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bulk_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('gr_no', sa.String(length=32), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='queued', nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('reporter', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['bulk_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bulk_items', schema=None) as batch_op:
        batch_op.create_index('ix_bulk_items_batch_status', ['batch_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bulk_items_case_id'), ['case_id'], unique=False)

    op.create_table('case_citations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('cited_title', sa.Text(), nullable=False),
    sa.Column('cited_gr_no', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('footnote_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_citations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_citations_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_citations_cited_gr_no'), ['cited_gr_no'], unique=False)

    op.create_table('case_digests_v2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=300), server_default='', nullable=False),
    sa.Column('scope_key', sa.String(length=300), server_default='', nullable=False),
    sa.Column('state', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('written', sa.Integer(), server_default='0', nullable=False),
    sa.Column('dropped', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('input_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('output_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'scope_key', name='uq_case_digests_v2_case_scope')
    )
    with op.batch_alter_table('case_digests_v2', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_digests_v2_created_at'), ['created_at'], unique=False)

    op.create_table('case_opinions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('author', sa.String(length=128), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_opinions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_opinions_case_id'), ['case_id'], unique=False)

    op.create_table('case_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('answer', sa.JSON(), nullable=True),
    sa.Column('state', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['bulk_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_questions', schema=None) as batch_op:
        batch_op.create_index('ix_case_questions_case_batch', ['case_id', 'batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_questions_created_at'), ['created_at'], unique=False)

    op.create_table('case_statutes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('statute_type', sa.String(length=16), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('raw', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_statutes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_statutes_case_id'), ['case_id'], unique=False)
        batch_op.create_index('ix_case_statutes_type_number', ['statute_type', 'number'], unique=False)

    op.create_table('case_subjects',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), server_default='student', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id', 'subject_id')
    )
    with op.batch_alter_table('case_subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_subjects_subject_id'), ['subject_id'], unique=False)

    op.create_table('catalog_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['catalog_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('catalog_numbers', schema=None) as batch_op:
        batch_op.create_index('ix_catalog_numbers_entry_id', ['entry_id'], unique=False)
        batch_op.create_index('ix_catalog_numbers_number_prefix', ['number'], unique=False)

    op.create_table('digests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=True),
    sa.Column('template', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('parser_version', sa.Integer(), nullable=True),
    sa.Column('ai_answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('digests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_digests_ai_answered_at'), ['ai_answered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_digests_upload_id'), ['upload_id'], unique=False)

    op.create_table('upload_citations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('raw_citation', sa.Text(), nullable=False),
    sa.Column('gr_no', sa.String(length=32), nullable=False),
    sa.Column('claimed_year', sa.Integer(), nullable=True),
    sa.Column('claimed_title', sa.Text(), nullable=True),
    sa.Column('claimed_date', sa.Date(), nullable=True),
    sa.Column('reporter', sa.String(length=64), nullable=True),
    sa.Column('matched_case_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('mismatches', sa.JSON(), nullable=True),
    sa.Column('unverified', sa.JSON(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['matched_case_id'], ['cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('upload_citations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upload_citations_gr_no'), ['gr_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_upload_citations_upload_id'), ['upload_id'], unique=False)

    op.create_table('case_footnotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('opinion_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('anchor', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opinion_id'], ['case_opinions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_footnotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_footnotes_case_id'), ['case_id'], unique=False)

    op.create_table('review_digest_edits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('digest_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['bulk_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['digest_id'], ['case_digests_v2.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'digest_id', 'section', name='uq_review_digest_edits_section')
    )
    # one digest per case per review, and one stand-alone (no review) per case: the web version's migration 0006
    op.execute("CREATE UNIQUE INDEX uq_digests_case_upload ON digests (case_id, COALESCE(upload_id, 0))")
    # the subject tags (the client's list), as the web version's migrations 0010 and 0013 leave them
    subjects = sa.table("subjects", sa.column("name", sa.String), sa.column("sort_order", sa.Integer))
    op.bulk_insert(subjects, [{"name": name, "sort_order": order} for order, name in enumerate(DEFAULT_SUBJECTS, start=1)])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_digest_edits')
    with op.batch_alter_table('case_footnotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_footnotes_case_id'))

    op.drop_table('case_footnotes')
    with op.batch_alter_table('upload_citations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upload_citations_upload_id'))
        batch_op.drop_index(batch_op.f('ix_upload_citations_gr_no'))

    op.drop_table('upload_citations')
    with op.batch_alter_table('digests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_digests_upload_id'))
        batch_op.drop_index(batch_op.f('ix_digests_ai_answered_at'))

    op.drop_table('digests')
    with op.batch_alter_table('catalog_numbers', schema=None) as batch_op:
        batch_op.drop_index('ix_catalog_numbers_number_prefix')
        batch_op.drop_index('ix_catalog_numbers_entry_id')

    op.drop_table('catalog_numbers')
    with op.batch_alter_table('case_subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_subjects_subject_id'))

    op.drop_table('case_subjects')
    with op.batch_alter_table('case_statutes', schema=None) as batch_op:
        batch_op.drop_index('ix_case_statutes_type_number')
        batch_op.drop_index(batch_op.f('ix_case_statutes_case_id'))

    op.drop_table('case_statutes')
    with op.batch_alter_table('case_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_questions_created_at'))
        batch_op.drop_index('ix_case_questions_case_batch')

    op.drop_table('case_questions')
    with op.batch_alter_table('case_opinions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_opinions_case_id'))

    op.drop_table('case_opinions')
    with op.batch_alter_table('case_digests_v2', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_digests_v2_created_at'))

    op.drop_table('case_digests_v2')
    with op.batch_alter_table('case_citations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_citations_cited_gr_no'))
        batch_op.drop_index(batch_op.f('ix_case_citations_case_id'))

    op.drop_table('case_citations')
    with op.batch_alter_table('bulk_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bulk_items_case_id'))
        batch_op.drop_index('ix_bulk_items_batch_status')

    op.drop_table('bulk_items')
    op.drop_table('uploads')
    op.drop_table('subjects')
    op.drop_table('month_indexes')
    op.drop_table('job_locks')
    op.drop_table('catalog_months')
    with op.batch_alter_table('catalog_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_catalog_entries_year_month')
        batch_op.drop_index('ix_catalog_entries_title_trgm')

    op.drop_table('catalog_entries')
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index('ix_cases_title_trgm')
        batch_op.drop_index(batch_op.f('ix_cases_main_case_id'))
        batch_op.drop_index(batch_op.f('ix_cases_gr_no'))

    op.drop_table('cases')
    op.drop_table('bulk_batches')
    # ### end Alembic commands ###
