/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LookupRouteImport } from './routes/lookup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as CasesIndexRouteImport } from './routes/cases.index'
import { Route as CasesCaseIdRouteImport } from './routes/cases.$caseId'
import { Route as ReviewsIndexRouteImport } from './routes/reviews.index'
import { Route as ReviewsBatchIdRouteImport } from './routes/reviews.$batchId'
import { Route as CasesCaseIdDecisionRouteImport } from './routes/cases.$caseId_.decision'
import { Route as CasesCaseIdDigestRouteImport } from './routes/cases.$caseId_.digest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LookupRoute = LookupRouteImport.update({
  id: '/lookup',
  path: '/lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdRoute = CasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsIndexRoute = ReviewsIndexRouteImport.update({
  id: '/reviews/',
  path: '/reviews/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsBatchIdRoute = ReviewsBatchIdRouteImport.update({
  id: '/reviews/$batchId',
  path: '/reviews/$batchId',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdDecisionRoute = CasesCaseIdDecisionRouteImport.update({
  id: '/cases/$caseId_/decision',
  path: '/cases/$caseId/decision',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdDigestRoute = CasesCaseIdDigestRouteImport.update({
  id: '/cases/$caseId_/digest',
  path: '/cases/$caseId/digest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guide': typeof GuideRoute
  '/library': typeof LibraryRoute
  '/lookup': typeof LookupRoute
  '/search': typeof SearchRoute
  '/upload': typeof UploadRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/reviews/$batchId': typeof ReviewsBatchIdRoute
  '/cases/': typeof CasesIndexRoute
  '/reviews/': typeof ReviewsIndexRoute
  '/cases/$caseId/decision': typeof CasesCaseIdDecisionRoute
  '/cases/$caseId/digest': typeof CasesCaseIdDigestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guide': typeof GuideRoute
  '/library': typeof LibraryRoute
  '/lookup': typeof LookupRoute
  '/search': typeof SearchRoute
  '/upload': typeof UploadRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/reviews/$batchId': typeof ReviewsBatchIdRoute
  '/cases': typeof CasesIndexRoute
  '/reviews': typeof ReviewsIndexRoute
  '/cases/$caseId/decision': typeof CasesCaseIdDecisionRoute
  '/cases/$caseId/digest': typeof CasesCaseIdDigestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guide': typeof GuideRoute
  '/library': typeof LibraryRoute
  '/lookup': typeof LookupRoute
  '/search': typeof SearchRoute
  '/upload': typeof UploadRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/reviews/$batchId': typeof ReviewsBatchIdRoute
  '/cases/': typeof CasesIndexRoute
  '/reviews/': typeof ReviewsIndexRoute
  '/cases/$caseId_/decision': typeof CasesCaseIdDecisionRoute
  '/cases/$caseId_/digest': typeof CasesCaseIdDigestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/guide'
    | '/library'
    | '/lookup'
    | '/search'
    | '/upload'
    | '/cases/$caseId'
    | '/reviews/$batchId'
    | '/cases/'
    | '/reviews/'
    | '/cases/$caseId/decision'
    | '/cases/$caseId/digest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/guide'
    | '/library'
    | '/lookup'
    | '/search'
    | '/upload'
    | '/cases/$caseId'
    | '/reviews/$batchId'
    | '/cases'
    | '/reviews'
    | '/cases/$caseId/decision'
    | '/cases/$caseId/digest'
  id:
    | '__root__'
    | '/'
    | '/guide'
    | '/library'
    | '/lookup'
    | '/search'
    | '/upload'
    | '/cases/$caseId'
    | '/reviews/$batchId'
    | '/cases/'
    | '/reviews/'
    | '/cases/$caseId_/decision'
    | '/cases/$caseId_/digest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuideRoute: typeof GuideRoute
  LibraryRoute: typeof LibraryRoute
  LookupRoute: typeof LookupRoute
  SearchRoute: typeof SearchRoute
  UploadRoute: typeof UploadRoute
  CasesCaseIdRoute: typeof CasesCaseIdRoute
  ReviewsBatchIdRoute: typeof ReviewsBatchIdRoute
  CasesIndexRoute: typeof CasesIndexRoute
  ReviewsIndexRoute: typeof ReviewsIndexRoute
  CasesCaseIdDecisionRoute: typeof CasesCaseIdDecisionRoute
  CasesCaseIdDigestRoute: typeof CasesCaseIdDigestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookup': {
      id: '/lookup'
      path: '/lookup'
      fullPath: '/lookup'
      preLoaderRoute: typeof LookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/': {
      id: '/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId': {
      id: '/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof CasesCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/': {
      id: '/reviews/'
      path: '/reviews'
      fullPath: '/reviews/'
      preLoaderRoute: typeof ReviewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/$batchId': {
      id: '/reviews/$batchId'
      path: '/reviews/$batchId'
      fullPath: '/reviews/$batchId'
      preLoaderRoute: typeof ReviewsBatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId_/decision': {
      id: '/cases/$caseId_/decision'
      path: '/cases/$caseId/decision'
      fullPath: '/cases/$caseId/decision'
      preLoaderRoute: typeof CasesCaseIdDecisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId_/digest': {
      id: '/cases/$caseId_/digest'
      path: '/cases/$caseId/digest'
      fullPath: '/cases/$caseId/digest'
      preLoaderRoute: typeof CasesCaseIdDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuideRoute: GuideRoute,
  LibraryRoute: LibraryRoute,
  LookupRoute: LookupRoute,
  SearchRoute: SearchRoute,
  UploadRoute: UploadRoute,
  CasesCaseIdRoute: CasesCaseIdRoute,
  ReviewsBatchIdRoute: ReviewsBatchIdRoute,
  CasesIndexRoute: CasesIndexRoute,
  ReviewsIndexRoute: ReviewsIndexRoute,
  CasesCaseIdDecisionRoute: CasesCaseIdDecisionRoute,
  CasesCaseIdDigestRoute: CasesCaseIdDigestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
