/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as LookupRouteImport } from './routes/lookup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as CasesIndexRouteImport } from './routes/cases.index'
import { Route as CasesCaseIdRouteImport } from './routes/cases.$caseId'
import { Route as ReviewsIndexRouteImport } from './routes/reviews.index'
import { Route as ReviewsReviewIdRouteImport } from './routes/reviews.$reviewId'
import { Route as CasesCaseIdDecisionRouteImport } from './routes/cases.$caseId_.decision'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const LookupRoute = LookupRouteImport.update({
  id: '/lookup',
  path: '/lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdRoute = CasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsIndexRoute = ReviewsIndexRouteImport.update({
  id: '/reviews/',
  path: '/reviews/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsReviewIdRoute = ReviewsReviewIdRouteImport.update({
  id: '/reviews/$reviewId',
  path: '/reviews/$reviewId',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdDecisionRoute = CasesCaseIdDecisionRouteImport.update({
  id: '/cases/$caseId_/decision',
  path: '/cases/$caseId/decision',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guide': typeof GuideRoute
  '/lookup': typeof LookupRoute
  '/search': typeof SearchRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/reviews/$reviewId': typeof ReviewsReviewIdRoute
  '/cases/': typeof CasesIndexRoute
  '/reviews/': typeof ReviewsIndexRoute
  '/cases/$caseId/decision': typeof CasesCaseIdDecisionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guide': typeof GuideRoute
  '/lookup': typeof LookupRoute
  '/search': typeof SearchRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/reviews/$reviewId': typeof ReviewsReviewIdRoute
  '/cases': typeof CasesIndexRoute
  '/reviews': typeof ReviewsIndexRoute
  '/cases/$caseId/decision': typeof CasesCaseIdDecisionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guide': typeof GuideRoute
  '/lookup': typeof LookupRoute
  '/search': typeof SearchRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/reviews/$reviewId': typeof ReviewsReviewIdRoute
  '/cases/': typeof CasesIndexRoute
  '/reviews/': typeof ReviewsIndexRoute
  '/cases/$caseId_/decision': typeof CasesCaseIdDecisionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/guide'
    | '/lookup'
    | '/search'
    | '/cases/$caseId'
    | '/reviews/$reviewId'
    | '/cases/'
    | '/reviews/'
    | '/cases/$caseId/decision'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/guide'
    | '/lookup'
    | '/search'
    | '/cases/$caseId'
    | '/reviews/$reviewId'
    | '/cases'
    | '/reviews'
    | '/cases/$caseId/decision'
  id:
    | '__root__'
    | '/'
    | '/guide'
    | '/lookup'
    | '/search'
    | '/cases/$caseId'
    | '/reviews/$reviewId'
    | '/cases/'
    | '/reviews/'
    | '/cases/$caseId_/decision'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuideRoute: typeof GuideRoute
  LookupRoute: typeof LookupRoute
  SearchRoute: typeof SearchRoute
  CasesCaseIdRoute: typeof CasesCaseIdRoute
  ReviewsReviewIdRoute: typeof ReviewsReviewIdRoute
  CasesIndexRoute: typeof CasesIndexRoute
  ReviewsIndexRoute: typeof ReviewsIndexRoute
  CasesCaseIdDecisionRoute: typeof CasesCaseIdDecisionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookup': {
      id: '/lookup'
      path: '/lookup'
      fullPath: '/lookup'
      preLoaderRoute: typeof LookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/': {
      id: '/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId': {
      id: '/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof CasesCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/': {
      id: '/reviews/'
      path: '/reviews'
      fullPath: '/reviews/'
      preLoaderRoute: typeof ReviewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/$reviewId': {
      id: '/reviews/$reviewId'
      path: '/reviews/$reviewId'
      fullPath: '/reviews/$reviewId'
      preLoaderRoute: typeof ReviewsReviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId_/decision': {
      id: '/cases/$caseId_/decision'
      path: '/cases/$caseId/decision'
      fullPath: '/cases/$caseId/decision'
      preLoaderRoute: typeof CasesCaseIdDecisionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuideRoute: GuideRoute,
  LookupRoute: LookupRoute,
  SearchRoute: SearchRoute,
  CasesCaseIdRoute: CasesCaseIdRoute,
  ReviewsReviewIdRoute: ReviewsReviewIdRoute,
  CasesIndexRoute: CasesIndexRoute,
  ReviewsIndexRoute: ReviewsIndexRoute,
  CasesCaseIdDecisionRoute: CasesCaseIdDecisionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
